apiVersion: v1
kind: Service
metadata:
  name: cip-api
  namespace: cip
  labels:
    app.kubernetes.io/name: cip-api
    app.kubernetes.io/part-of: content-insights-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cip-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
